name: Maven Tests & Allure

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # обновил версии

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'  # кэш ускоряет

      - name: Run Maven tests & generate Allure
        run: mvn clean test allure:report  # твоя основная команда!

      - name: Checkout gh-pages for history
        if: always()
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report with history
        if: always()
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: target/allure-results  # Maven путь по умолчанию
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4  # обновил
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report  # или allure-history для истории
          publish_branch: gh-pages
